# Generated by Django 4.2.2 on 2023-06-16 14:41
import logging
from django.db import migrations


logger = logging.getLogger(__name__)


def _get_models(apps):
    return (
        apps.get_model("tradespeople", "Company"),
        apps.get_model("tradespeople", "Tradesperson"),
    )


def forwards(apps, _):
    Company, Tradesperson = _get_models(apps)

    companies_to_create = (
        Company(name="The Boiler Co."),
        Company(name="Maximum Solar Installations"),
    )
    companies = Company.objects.bulk_create(companies_to_create)
    logger.info(f"Created {len(companies)} Company instances.")

    tradespeople_to_create = []
    for company in enumerate(companies):
        for idx in range(3):
            tradespeople_to_create.append(
                Tradesperson(
                    first_name="Employee",
                    second_name=f"#{idx}",
                    company=company,
                )
            )
    tradespeople = Tradesperson.objects.bulk_create(tradespeople_to_create)
    logger.info(f"Created {len(tradespeople)} Tradesperson instances.")


def backwards(apps, _):
    Company, Tradesperson = _get_models(apps)
    Company.objects.all().delete()
    Tradesperson.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tradespeople", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
